spring.application.name=user-service
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port= 8090

secretKey=d9e9cd5c88412cecc863e9c82fa11e1acb51caf70c2ed960b36be7371c9775a3
